In [1]:
import numpy as np

#### Task 1

In [7]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape(2, 5).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
a_mean = np.mean(a, axis=0)
a_mean

array([2. , 8.4])

#### Task 2

In [15]:
a_centered = a - a_mean
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Task 3

In [21]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [28]:
a_centered_sp/(a.shape[0] - 1)

2.0

#### Task 4

In [33]:
a_centered_sp = np.cov(a.T)[0, 1]
a_centered_sp

2.0